config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  namespace :admin do
    root to: "homes#top"
    resources :environments, except: [:new, :show]
    resources :prefectures, except: [:new, :show]
    resources :users, only: [:index, :show, :edit, :update]
    #不適切な投稿削除用
    resources :posts, only: [:show, :destroy] do
      #不適切なレビューやコメント削除用
      resources :post_comments, only: [:destroy]
    end
  end

  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'puclic/passwords',
  }
  
  scope module: :public do
    root to: "homes#top"
    get "how_to" => "homes#how_to"
    
    devise_scope :user do
      #ゲストログイン用ルート
      post 'user/guest_sign_in' => 'sessions#guest_sign_in'
    end
    
    ##urlにidが含まれないようにuserはそれぞれurlを指定しています。
    #会員マイページ
    get 'users/mypage' => 'users#show', as: 'mypage'
    #users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えています。
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    put 'users/information' => 'users#update'
    #お気に入り一覧画面
    get 'users/favorites' => 'users#favorites', as: 'user_favorites'
    #会員退会確認画面
    get 'users/confirm_withdraw' => 'users#confirm_withdraw', as: 'confirm_withdraw'
    #退会アクション
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      post "post_comments/comment_upload_image", to: "post_comments#comment_upload_image"
      resource :favorites, only: [:create, :destroy]
    end
    post "posts/upload_image", to: "posts#upload_image"
    
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/environment.rb
class Environment < ApplicationRecord
  
  has_many :posts, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/environments_controller.rb
class Admin::EnvironmentsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_environment, only: [:show, :edit, :update, :destroy]
  
  def index
    @environment = Environment.new
    # @environments = Environment.all
    @environments = Environment.all.page(params[:page])
  end

  def create
    @environment = Environment.new(environment_params)
    if @environment.save
      redirect_to admin_environments_path, notice: "環境タグの新規登録に成功しました。"
    else
      # @environments = Environment.all
      @environments = Environment.page(params[:page])
      render 'index', notice: "環境タグの新規登録に失敗しました。"
    end
  end

  def edit
  end

  def update
    if @environment.update(environment_params)
      redirect_to admin_environments_path, notice: "環境タグの変更に成功しました。"
    else
      render "edit", notice: "環境タグの変更に失敗しました。"
    end
  end

  def destroy
    @environment.destroy
    redirect_to admin_environments_path, notice: "環境タグの削除に成功しました。"
  end

  private

  def environment_params
    params.require(:environment).permit(:name)
  end
  
  def set_environment
    @environment = Environment.find(params[:id])
  end
  
end

app/helpers/admin/environments_helper.rb
module Admin::EnvironmentsHelper
end

app/views/admin/environments/_form.html.erb
<%= form_with model:environment, url: url do |f| %>
	<%= render 'layouts/error_messages', resource: environment %>
	<%= f.label :name, "環境名:" %>
	<%= f.text_field :name %>
	<%= f.submit submit, class: "btn btn-primary ml2" %>
<% end %>

app/views/admin/environments/edit.html.erb
<div class='container px-5 px-sm-0  form-box'>
  <div class="row">
    <div class="offset-1 text-center">
      <h2 class="text-center px-3 py-3">
        <strong>環境タグ編集</strong>
      </h2>
    </div>
  </div>
  <div class='row'>
    <div class='col'>
      <div class="mb-3">
        <section class="inner">
          <% if admin_signed_in? %>
            <%= render 'admin/environments/form', environment: @environment, url: admin_environment_path(@environment), method: :PATCH, submit: '更新' %>
          <% end %>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/admin/environments/index.html.erb
<div class='container px-5 px-sm-0  form-box'>
  <div class="row">
    <div class="offset-1 text-center">
      <h2 class="text-center px-3 py-3">
        <strong>環境タグ管理</strong>
      </h2>
    </div>
  </div>
  <div class='row'>
    <div class='col'>
      <div class="mb-3">
        <h3>環境タグ新規登録</h3>
        <%= render 'admin/environments/form', environment: @environment, url: admin_environments_path, method: :POST, submit: '登録' %>
      </div>
      <div class="pt-3">
        <h3>環境一覧</h3>
        <table class="table table-hover table-inverse bg-light has_border">
          <thead>
            <tr>
              <th>ID</th>
              <th>環境名</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @environments.each do |environment| %>
              <tr>
                <td><%= environment.id %></td>
                <td><%= link_to environment.name, admin_root_path(environment_id: environment.id), class: "underline" %></td>
              <% if admin_signed_in? %>
                <td class="text-center"><%= link_to "編集", edit_admin_environment_path(environment), class: "btn btn-success" %></td>
                <td class="text-center"><%= link_to '削除', admin_environment_path(environment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger" %></td>
              <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @environments %>
      </div>
    </div>
  </div>
</div>