config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
  }

  namespace :admin do
    root to: "homes#top"
    resources :environments, except: [:new, :show]
    resources :prefectures, except: [:new, :show]
    resources :users, only: [:index, :show, :edit, :update]
    #不適切な投稿削除用
    resources :posts, only: [:show, :destroy] do
      #不適切なレビューやコメント削除用
      resources :post_comments, only: [:destroy]
    end
  end

  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'puclic/passwords',
  }
  
  scope module: :public do
    root to: "homes#top"
    get "how_to" => "homes#how_to"
    
    devise_scope :user do
      #ゲストログイン用ルート
      post 'user/guest_sign_in' => 'sessions#guest_sign_in'
    end
    
    ##urlにidが含まれないようにuserはそれぞれurlを指定しています。
    #会員マイページ
    get 'users/mypage' => 'users#show', as: 'mypage'
    #users/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えています。
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    put 'users/information' => 'users#update'
    #お気に入り一覧画面
    get 'users/favorites' => 'users#favorites', as: 'user_favorites'
    #会員退会確認画面
    get 'users/confirm_withdraw' => 'users#confirm_withdraw', as: 'confirm_withdraw'
    #退会アクション
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      post "post_comments/comment_upload_image", to: "post_comments#comment_upload_image"
      resource :favorites, only: [:create, :destroy]
    end
    post "posts/upload_image", to: "posts#upload_image"
    
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='footer'>
  <div class='bg-dark pt-2 pb-1'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p class="font3 text-light">CopyRight Infratop.inc  Yaei Lovers</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light">
    <div class="container">
      <div class="logo">
        <font size="5" class="text-light">
          <%= link_to (admin_signed_in? ? admin_root_path : root_path ), class: "nav-link text-light" do %>
            <i class="fas fa-campground"></i> Yaei Lovers
          <% end %>
        </font>
      </div>
      <a>野営地の共有・検索サイトです</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> トップへ
            <% end %>
          </li>
          <li>
            <%= link_to how_to_path, class: 'nav-link text-light' do %>
              <i class="fas fa-list"></i> 野営の心得
            <% end %>
          </li>
          <li>
            <%= link_to admin_users_path, class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> 会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_environments_path, class: 'nav-link text-light' do %>
              <i class="fas fa-tree"></i> 環境一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_prefectures_path, class: 'nav-link text-light' do %>
              <i class="fas fa-globe-asia"></i> 県名一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% elsif user_signed_in? %>
          <li>
            <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> トップへ
            <% end %>
          </li>
          <li>
            <%= link_to how_to_path, class: 'nav-link text-light' do %>
              <i class="fas fa-list"></i> 野営の心得
            <% end %>
          </li>
          <li>
            <%= link_to mypage_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user"></i> マイページ
            <% end %>
          </li>
          <li>
            <%= link_to new_post_path, class: 'nav-link text-light' do %>
              <i class="fas fa-folder-plus"></i> 新規投稿
            <% end %>
          </li>
          <li>
            <%= link_to posts_path, class: 'nav-link text-light' do %>
              <i class="fas fa-campground"></i> 野営地一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path, class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> トップへ
            <% end %>
          </li>
          <li>
            <%= link_to how_to_path, class: 'nav-link text-light' do %>
              <i class="fas fa-list"></i> 野営の心得
            <% end %>
          </li>
          <li>
            <%= link_to user_guest_sign_in_path, method: :post, class: 'nav-link text-light' do %>
              <i class="fas fa-eye"></i> ゲストログイン
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <nav class="navbar-expand-lg navbar-dark bg-dark text-center text-light center-block pb-3">
    <p class="font10">レッツ、ワイルドライフ！！ 野営して自然と一体になろう！</p>
  </nav>
</header>

app/views/layouts/_rule.html.erb
<div class="border text-bold text-light">
  <h2 class="text-center mt-3">野営十か条</h2>
  <a>➀ゴミは持って帰れ！</a></br>
  <a>➁近所に迷惑をかけない！</a></br>
  <a>➂直火禁止！</a></br>
  <a>➃火の処理は正しく</a></br>
  <a>➄飛び火、延焼に注意！</a></br>
  <a>➅雨天の川沿いなど、危険地は避ける</a></br>
  <a>➆野営は許可を取って</a></br>
  <a>➇野営場所は誰かに伝える</a></br>
  <a>➈獣に注意！</a></br>
  <a>➉野営は自己責任で</a></br>
</div>

app/views/layouts/_search.html.erb
<div class="border text-center text-light">
  <h3 class="text-center my-3">野営地検索</h3>
  <%= form_with model: post, url: posts_path, local: true, method: :get do |form| %>
  
    <div class="text-center">
      <%= form.label :prefecture_id, "都道府県" %>
      <a class="select_field text-center"><%= form.collection_select :prefecture_id, Prefecture.all, :id, :name %></a>
    </div>
    <div class="text-center">
      <%= form.label :environment_id, "環境" %>
      <a class="select_field"><%= form.collection_select :environment_id, Environment.all, :id, :name %></a>
    </div>
    
    <button type="submit">
      <i class="fas fa-search"></i> 検索
    </button>
    
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YaeiLovers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--app/javascript 配下でcssを管理します、必要に応じてapplication.scssにcssを記述、もしくは作成したcssファイルをapplication.jsにinportしてください。-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <div class="background_img main-size">
        <span><%= notice %></span>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>